#!/bin/sh

service_name=$1

usage="request-spot-fleet <service_name>"

if [ -z $service_name ] 
then
  echo $usage
  exit 1
fi

region=`grep region aws-config-tokyo.yml |awk '{print $2}'`

aws ec2 request-spot-fleet \
  --region $region \
  --spot-fleet-request-config file://spot-fleet-specifications/${service_name}.json 
